name: tunnel-ai-app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.25
  - pandas>=2.0
  - shiny>=1.0.0
  - shinywidgets>=0.3.0
  - plotly>=5.0
  - pytest>=8.0
  - pip:
      - -r requirements.txt
